### ISSUE TITLE
Replace aws-mfa with aws-vault

### ISSUE THREAD

**Issue by 0xdabbad00** [kevinslin/open-cdk#1]
I believe aws-vault[1] is a more widely used, featureful, and generally better solution than similar solutions out there such as aws-mfa that you mention.  I recommend mentioning aws-vault instead.

1. https://github.com/99designs/aws-vault

**Comment by kevinslin** [comment]
nice, wasn't aware of that. will update the guide :)

**Comment by kevinslin** [comment]
updated docs. also congrats on submitting the first issue :)  -> https://github.com/kevinslin/open-cdk/commit/7a8946ff50e729fd0068f0c0c8e06faffcc1fbb3
