### ISSUE TITLE
Simple ids naming section recommendation recommends PascalCase but uses camelCase

### ISSUE THREAD

**Issue by bharloe** [kevinslin/open-cdk#4]
From the guide:

> stick to pascalCase with no spaces, punctuation or underscores

According to techterms.com:

> PascalCase is a naming convention in which the first letter of each word in a compound word is capitalized.

> camelCase is a naming convention in which each word within a compound word is capitalized except for the first word.

Super pedantic issue but just thought I'd try to help out in the small way I can. Thanks for the resource, will definitely be coming back!

**Comment by kevinslin** [comment]
@bharloe thanks for the heads up. fixed :)
